# 📊 Introduction to NumPy

NumPy (Numerical Python) is a powerful library for numerical computing in Python. It provides support for arrays, matrices, and a large collection of mathematical functions to operate on these data structures.

## 📝 Key Features
- **N-Dimensional Arrays**: Efficient and powerful n-dimensional array object.
- **Mathematical Functions**: Comprehensive collection of mathematical functions for array operations.
- **Broadcasting**: Ability to perform operations on arrays of different shapes.
- **Performance**: Optimized for performance with support for vectorized operations, which are faster than traditional Python loops.

### Importing NumPy
First, you need to import the NumPy library. It's common practice to import it using the alias `np`.


In [2]:
import numpy as np

arr = np.array([1,2,3])
arr

array([1, 2, 3])

## 📝 Data Types

In [28]:
arr.dtype

dtype('int64')

## 📝 Dimensions

In [3]:
arr.ndim

1

In [4]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr.ndim

2

## 📝 Indexing

In [8]:
arr = np.array([1,2,3])
arr[::2]

array([1, 3])

In [9]:
arr[::-1]

array([3, 2, 1])

In [10]:
arr[1:3:1]

array([2, 3])

In [32]:
arr[arr>1]

array([2, 3])

## 📝 Search into arrays

In [14]:
np.where(arr == 2)

(array([1]),)

In [15]:
np.searchsorted(arr,3)

2

## 📝 Sort

In [33]:
arr5 = np.array([3,4,6])
arr5.sort()
arr5

array([3, 4, 6])

## 📝 Random number

In [18]:
from numpy import random
num = random.randint(10)
num

8

In [73]:
np.random.random((2,2))

array([[0.85716636, 0.09120176],
       [0.60791525, 0.28358069]])

## 📝 LineSpace for ploting

In [23]:
np.linspace(0,2,num = 5) #Used in plots

array([0. , 0.5, 1. , 1.5, 2. ])

## 📝 Identity Matrix

In [24]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

## 📝 Copy and View

In [30]:
arr2 = arr.copy()
arr2

array([1, 2, 3])

In [31]:
arr2 = arr.view()
arr2

array([1, 2, 3])

## 📝 Append and concate

In [35]:
np.append(arr2,arr5)

array([1, 2, 3, 3, 4, 6])

In [47]:
ar1 = np.array([[1,2],[3,4]])
ar2 = np.array([[5,6]])
np.concatenate((ar1,ar2),axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [50]:
ar1 = np.array([[1,2],[3,4]])
ar2 = np.array([[5],[6]])
np.concatenate((ar1,ar2),axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

## 📝 Unique

In [51]:
ar = np.array([1,2,2,3,3])
np.unique(ar)

array([1, 2, 3])

## 📝 Shape and Reshape

In [52]:
ar.shape

(5,)

In [53]:
ar.reshape(1,5)

array([[1, 2, 2, 3, 3]])

In [56]:
np.ravel(ar)

array([1, 2, 2, 3, 3])

## 📝 Split 

In [58]:
np.array_split(ar,5)

[array([1]), array([2]), array([2]), array([3]), array([3])]

In [61]:
np.hsplit(ar,5)

[array([1]), array([2]), array([2]), array([3]), array([3])]

## 📝 Ones and Zeros

In [71]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [72]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

## 📝 Joining

In [79]:
import numpy as np

ar = np.array([1, 2])
ar1 = np.array([3, 4])

result = np.dstack((ar, ar1))
print(result)

[[[1 3]
  [2 4]]]


In [127]:
np.corrcoef(ar,ar1)

array([[1., 1.],
       [1., 1.]])

## 📝 Statistical Numpy

In [80]:
np.mean(ar)

1.5

In [81]:
np.average(ar)

1.5

In [82]:
np.std(ar)

0.5

In [83]:
np.median(ar)

1.5

In [85]:
np.var(ar)

0.25

In [87]:
np.max(ar)

2

In [86]:
np.min(ar)

1

In [88]:
np.sum(ar)

3

In [89]:
np.exp(ar)

array([2.71828183, 7.3890561 ])

In [93]:
arr = ar + ar1
arr

array([4, 6])

In [3]:
import numpy as np

arr = np.array([1, 2 ,3, 4, 5])
np.percentile(arr,25)

2.0

In [4]:
np.quantile(arr,0.5)

3.0

## 📝 Linear Algebra

In [94]:
np.dot(ar,ar1)

11

In [95]:
ar @ ar1

11

In [102]:
import numpy as np

matrix = np.array([[1, 2], [3, 4]])

arr = np.linalg.det(matrix)
arr

-2.0000000000000004

In [103]:
np.linalg.inv(matrix)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [104]:
np.linalg.eig(matrix)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))

## 📝 Dealing with Missing Values

In [107]:
arr = np.array([1,2,3,np.nan])
arr

array([ 1.,  2.,  3., nan])

In [111]:
arr[~(np.isnan(arr))]

array([1., 2., 3.])

## 📝 Flip

In [121]:
import numpy as np

matrix = np.array([[1, 2], [3, 4]])

np.flip(matrix,axis = 1)

array([[2, 1],
       [4, 3]])

In [122]:
np.flip(matrix,axis = 0)

array([[3, 4],
       [1, 2]])

## 📝 Set Theory

In [128]:
arr2 = np.array([[1, 2 ,3, 4, 5 ,6]])
np.union1d(arr,arr2)

array([1, 2, 3, 4, 5, 6])

In [129]:
arr2 = np.array([[1, 2 ,3, 4, 5 ,6]])
np.intersect1d(arr,arr2)

array([1, 2, 3, 4, 5])

In [132]:
np.array_equal(arr,arr2)

False

In [133]:
np.in1d(arr,arr2)

array([ True,  True,  True,  True,  True])

### Subset

In [134]:
np.all(arr)

True

### Superset

In [135]:
np.all(np.in1d(arr,arr2))

True